src/market/urls.py
from django.urls import path
from market import views


app_name = 'market'

urlpatterns = [
    path('admin_register/', views.AdminRegisterView.as_view(), name='admin_register'),
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('customer_register/', views.CustomerRegisterView.as_view(), name='customer_register'),
]

src/shop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from market.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('', LoginView.as_view(), name='login')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/market/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __repr__(self):
        return "{}".format(self.name)


class Item(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    price = models.IntegerField(default=0)
    quanity = models.IntegerField(default=0)
    picture = models.ImageField(upload_to='item_images', blank=True)
    is_removed = models.BooleanField(default=False)

    def __repr__(self):
        return "{} {} {} {} {}".format(self.category, self.name, self.price, self.quanity, self.picture)


class Administrator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    registrated_at = models.DateTimeField(default=datetime.now)
    avatar = models.ImageField(upload_to='admin_profile_images', blank=True)

    def __repr__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    registrated_at = models.DateTimeField(default=datetime.now)
    avatar = models.ImageField(upload_to='customer_profile_images', blank=True)

    def __repr__(self):
        return self.user.username


class Stock(models.Model):
    administrator = models.ForeignKey(Administrator, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)

    def __repr__(self):
        return "{} {} {}".format(self.administrator, self.item, self.name)


class MyBug(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    buy_time = models.DateTimeField(default=datetime.now)

    def __repr__(self):
        return "{} {} {}".format(self.customer, self.item, self.buy_time)

src/market/forms.py
from django import forms
from django.contrib.auth.models import User
from market.models import Category, Item, Administrator, Customer, Stock, MyBug


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=100, help_text="Please enter the category name.")

    class Meta:
        model = Category
        fields = ('name',)


class ItemForm(forms.ModelForm):
    name = forms.CharField(max_length=100, help_text="Please enter the name of the Item.")
    price = forms.IntegerField(max_value=1000000, help_text="Please enter the price of the Item.")
    quanity = forms.IntegerField(max_value=1000000, help_text="Please enter the quanity of the Item.")
    is_removed = forms.BooleanField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Item
        exclude = ('category',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class AdministratorForm(forms.ModelForm):
    class Meta:
        model = Administrator
        fields = ('avatar',)


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('avatar',)


class StockForm(forms.ModelForm):
    name = forms.CharField(max_length=100, help_text="Please enter the Stock name.")

    class Meta:
        model = Stock
        exclude = ('administrator', )

src/market/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views import View
from market.forms import UserForm, AdministratorForm, CustomerForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponse
from market.models import Administrator
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


class AdminRegisterView(View):
    def get(self, request):
        return render(request, 'admin_register.html')

    def post(self, request):
        registered = False
        if request.method == 'POST':
            user_form = UserForm(data=request.POST)
            admin_form = AdministratorForm(data=request.POST)
            if user_form.is_valid() and admin_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()
                admin = admin_form.save(commit=False)
                admin.user = user
                if 'avatar' in request.FILES:
                    admin.avatar = request.FILES['avatar']
                admin.save()
                registered = True
            else:
                print(user_form.errors, admin_form.errors)
        else:
            user_form = UserForm
            admin_form = AdministratorForm()
        return render(request, 'admin_register.html', {'user_form': user_form,
                                                       'admin_form': admin_form,
                                                       'registered': registered})


class CustomerRegisterView(View):
    def get(self, request):
        return render(request, 'customer_register.html')

    def post(self, request):
        registered = False
        if request.method == 'POST':
            user_form = UserForm(data=request.POST)
            customer_form = CustomerForm(data=request.POST)
            if user_form.is_valid() and customer_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()
                customer = customer_form.save(commit=False)
                customer.user = user
                if 'avatar' in request.FILES:
                    customer.avatar = request.FILES['avatar']
                customer.save()
                registered = True
            else:
                print(user_form.errors, customer_form.errors)
        else:
            user_form = UserForm
            customer_form = CustomerForm()
        return render(request, 'customer_register.html', {'user_form': user_form,
                                                          'customer_form': customer_form,
                                                          'registered': registered})


class LoginView(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                if Administrator.objects.filter(user=user):
                    login(request, user)
                    return redirect(reverse('market:my_stock'))
                else:
                    login(request, user)
                    return redirect(reverse('market:stock_list'))
            else:
                print("Invalid login details: {0}, {1}".format(username, password))
        else:
            render(request, 'login.html')


class LogoutView(View):
    @method_decorator(login_required)
    def get(self, request):
        logout(request)
        return redirect(reverse('market:login'))

src/templates/market/admin_register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
    Admin Register
{% endblock %}
{% block body_block %}
    <h1>Register Here</h1>
    {% if registered %}
        <strong>Thank you for registering dear Admin!</strong>
    {% else %}
        <strong>Register Here Shop Administrator!</strong>
        <form id="user_form" method="post" action="{% url 'market:admin_register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ admin_form.as_p }}
            <input type="submit" name="submit" value="Register"/>
        </form>
    {% endif %}
{% endblock %}

src/templates/market/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Market -
    {% block title_block %}
        Welcome to our online shop!
    {% endblock %}
    </title>
</head>
<body>
    <div>
        {% block body_block%}
        {% endblock %}
    </div>
    {% if user.is_authenticated %}
        <li><a href="{% url 'market:logout' %}">Logout</a></li>
    {% else %}
        <li><a href="{% url 'market:login' %}">Login</a></li>
        <li><a href="{% url 'market:admin_register' %}">Register like Admin</a></li>
        <li><a href="{% url 'market:customer_register' %}">Register like Customer</a></li>
    {% endif %}
</body>
</html>

src/templates/market/customer_register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
    Customer Register
{% endblock %}
{% block body_block %}
    <h1>Register Here</h1>
    {% if registered %}
        <strong>Thank you for registering dear Customer!</strong>
    {% else %}
        <strong>Registered Here dear Customer</strong>
        <form id="user_form" method="post" action="{% url 'market:customer_register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ customer_form.as_p }}
            <input type="submit" name="submit" value="Register"/>
        </form>
    {% endif %}
{% endblock %}

src/templates/market/login.html
{% extends 'base.html' %}
{% load static %}
{% block tittle_block %}
    Login
{% endblock %}
{% block body_block %}
    <h1>Login to Shop</h1>
    <form id="login_form" method="post" action="{% url 'market:login' %}">
        {% csrf_token %}
        Username:<input type="text" name="username" value="" size="50"/>
        <br />
        Password:<input type="password" name="password" value="" size="50"/>
        <br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}